# Generated by Django 5.1.1 on 2025-09-15 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='key',
        ),
        migrations.AddField(
            model_name='apikey',
            name='read_key',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='write_key',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='api.customer'),
        ),
    ]
